// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLd2eoE8YUW6a_JY1d9EAJ1pVPpP8rCbc',
    appId: '1:793772436224:web:125e0145a1c15bed56e1e5',
    messagingSenderId: '793772436224',
    projectId: 'catalyst-2580-firebase',
    authDomain: 'catalyst-2580-firebase.firebaseapp.com',
    storageBucket: 'catalyst-2580-firebase.appspot.com',
    measurementId: 'G-J0THC0TWYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9oZBB6CeypXL2mrP5voMS1Mjh6ml0Izw',
    appId: '1:793772436224:android:f2bf94c6a2e1cd2656e1e5',
    messagingSenderId: '793772436224',
    projectId: 'catalyst-2580-firebase',
    storageBucket: 'catalyst-2580-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMc1r7-UXxBrOvjwcpLJe9_BiRIIjfVlU',
    appId: '1:793772436224:ios:45adbebde84fb7c056e1e5',
    messagingSenderId: '793772436224',
    projectId: 'catalyst-2580-firebase',
    storageBucket: 'catalyst-2580-firebase.appspot.com',
    iosBundleId: 'com.example.catalyst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMc1r7-UXxBrOvjwcpLJe9_BiRIIjfVlU',
    appId: '1:793772436224:ios:45adbebde84fb7c056e1e5',
    messagingSenderId: '793772436224',
    projectId: 'catalyst-2580-firebase',
    storageBucket: 'catalyst-2580-firebase.appspot.com',
    iosBundleId: 'com.example.catalyst',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLd2eoE8YUW6a_JY1d9EAJ1pVPpP8rCbc',
    appId: '1:793772436224:web:c9140b58c2098d1756e1e5',
    messagingSenderId: '793772436224',
    projectId: 'catalyst-2580-firebase',
    authDomain: 'catalyst-2580-firebase.firebaseapp.com',
    storageBucket: 'catalyst-2580-firebase.appspot.com',
    measurementId: 'G-F57L2JFD7V',
  );

}